title: Startpage Emporium
description: >
    A curated showcase of startpages for your browser by 0XE4. Currently listing over 40 beautiful startpages, with regular updates.
baseurl: ""

# Build settings
exclude: ["README.md", "portfolio.sublime-project", "portfolio.sublime-workspace"]
permalink: pretty
gems:
  - jekyll-sitemap
